name: Elixir CI

on:
  pull_request:
  push:
    branches:
      - main

env:
  ELIXIR_VERSION: 1.13
  OTP_VERSION: 24.2
  MIX_ENV: test
  WASMEX_BUILD: true

jobs:
  deps:
    runs-on: ubuntu-latest
    outputs:
      deps-cache-key: ${{ steps.get-cache-key.outputs.key }}
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          default: true

      - id: get-cache-key
        run: echo "::set-output name=key::mix-${{ env.ELIXIR_VERSION }}-${{ env.OTP_VERSION }}-${{ hashFiles('**/mix.lock') }}"

      - uses: actions/cache@v2
        id: cache-deps
        with:
          path: |
            deps
            _build
          key: ${{ steps.get-cache-key.outputs.key }}

      - run: mix do deps.get, deps.compile
        if: steps.cache-deps.outputs.cache-hit != 'true'

  credo:
    needs: deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - uses: actions/cache@v2
        id: cache-deps
        with:
          path: |
            deps
            _build
          key: ${{ needs.deps.outputs.deps-cache-key }}

      - run: mix credo

  format:
    needs: deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - run: mix format --check-formatted

  dialyzer:
    needs: deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - uses: actions/cache@v2
        id: cache-deps
        with:
          path: |
            deps
            _build
          key: ${{ needs.deps.outputs.deps-cache-key }}

      - uses: actions/cache@v2
        id: plt-cache
        with:
          path: priv/plts
          key: v2-plt-${{ env.ELIXIR_VERSION }}-${{ env.OTP_VERSION }}

      - run: mix dialyzer --plt
        if: steps.plt-cache.outputs.cache-hit != 'true'

      - run: mix dialyzer

  docs:
    needs: deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - uses: actions/cache@v2
        id: cache-deps
        with:
          path: |
            deps
            _build
          key: ${{ needs.deps.outputs.deps-cache-key }}

      - run: mix docs

  test:
    needs: deps
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ env.OTP_VERSION }}
          elixir-version: ${{ env.ELIXIR_VERSION }}

      - uses: actions/cache@v2
        id: cache-deps
        with:
          path: |
            deps
            _build
          key: ${{ needs.deps.outputs.deps-cache-key }}

      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
          default: true

      - name: Add targets
        run: |
          rustup target add wasm32-unknown-unknown
          rustup target add wasm32-wasi

      - uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: elixir-cargo-${{ hashFiles('**/Cargo.lock') }}

      - run: mix test
